### ISSUE TITLE
Problem with NilSerial

### ISSUE THREAD

**Issue by markthepiggy** [greiman/NilRTOS-Arduino#1]
Hi,

I hope you can help.  I have a thread that monitors incoming serial communications but it only reads 3 characters - the first 2 and the last one.

For instance, if I enter 123456 and press send in the arduino serial monitor, I get this:

`----------------------SerialIn = 126`

The arduino library code in Hardware.h/.cpp *works( as expected.

I have looked at the code for Serial.read. It seems pretty straightforward and just gets a character from the USB data register.

``` C++
/**
 *  Unbuffered read
 *  @return -1 if no character is available or an available character.
 */
int NilSerialClass::read() {
  if (UCSR0A & (1 << RXC0)) return UDR0;
  return -1;
}
```

I have tried with different baud rates (down to 2400) with no change in behaviour.

Here is the code: (comment out the #define in line 2 to use default, working Serial implementation)

``` C++
#include <NilSerial.h>
#define Serial NilSerial

char buffer[11];
int offset;

void setup()
{
  Serial.begin(115200);
  offset = 0;
  memset(buffer, 0, sizeof(buffer));
}

void loop()
{
  int value = Serial.read();
  if (value == -1)
  {
    if (offset)
    {
      Serial.print("SerialIn");
      Serial.println(buffer);
      offset = 0;
      memset(buffer, 0, sizeof(buffer));
    }    
//    nilThdSleep(1);     
  }
  else
  {
    //psPrintf(Serial, "X");       
    buffer[offset++] = value; 
  }

}
```

I'm now stuck. Any help would be appreciated.

Regards,
Mark

**Comment by greiman** [comment]
NilSerial is a simple unbuffered library intended to save RAM/flash.  You will miss input characters in a program like yours.  With no buffering, print blocks while several characters are printed so you miss input characters.

NilSerial is good for debug output and simple input where you wait until all input is captured.

This echo program demonstrates the problem.

``` c++
#include <NilSerial.h>
#define Serial NilSerial

void setup(){
  Serial.begin(115200);
}

void loop() {
  int value = Serial.read();
  if (value != -1) Serial.write(value);
  delayMicroseconds(160);
}
```

If you input the line "1234567890"

It will print "1234680"

If you remove the delayMicroseconds, it will print "1234567890"
