### ISSUE TITLE
nilSemWaitTimeout()  returning NIL_MSG_OK on timeout condition

### ISSUE THREAD

**Issue by dmemphis** [greiman/NilRTOS-Arduino#3]
On 1.8.0 IDE on UNO:

On this fragment:

SEMAPHORE_DECL(semRGB, 0);
...
NIL_THREAD(ThreadRGB, arg) {
while (true) {
  static systime_t WaitMillis = 10;  
   msg_t semmsg = nilSemWaitTimeout(&semRGB, WaitMillis);
   if (semmsg == NIL_MSG_TMO) {
   ... 
   } else {  // got signaled
   ...
   }
}
... on timeout conditions never enters the if true block.  semmsg prints out as 0, which I take is NIL_MSG_OK.  The elapsed time of the requested timeout is correct.
As such one cannot distinguish between a timeout and receiving a message as per the documentation:

/**
 * @brief   Performs a wait operation on a semaphore with timeout specification.
 *
 * @param[in] sp        pointer to a @p semaphore_t structure
 * @param[in] timeout   the number of ticks before the operation timeouts,
 *                      the following special values are allowed:
 *                      - @a TIME_IMMEDIATE immediate timeout.
 *                      - @a TIME_INFINITE no timeout.
 *                      .
 * @return              A message specifying how the invoking thread has been
 *                      released from the semaphore.
 * @retval NIL_MSG_OK   if the thread has not stopped on the semaphore or the
 *                      semaphore has been signaled.
 * @retval NIL_MSG_RST  if the semaphore has been reset using @p nilSemReset().
 * @retval NIL_MSG_TMO  if the semaphore has not been signaled or reset within
 *                      the specified timeout.
 *
 * @api
 */
msg_t nilSemWaitTimeout(semaphore_t *sp, systime_t timeout) {
  msg_t msg;

  nilSysLock();
  msg = nilSemWaitTimeoutS(sp, timeout);
  nilSysUnlock();
  return msg;
}
 
There is evidence that the semiphore/task system is set up properly as
nilSemWait() properly fires when signaled.

Is there a reference manual that is generated by these headers?
I find the online reference here: http://chibios.sourceforge.net/docs3/nil/structnil__semaphore.html
confusing because it reads like a mashup of Chibi and NIL, with many references to ch
prefixed items.

**Comment by dmemphis** [comment]
Perhaps not cosher - I'm firing the semiphore from a main loop-
unlike the examples I did not set up a thread for the main loop- just the one
I wanted to trigger.  When the thread simply used nilSemiWait(), this worked fine though.
void loop() 
{
  static long HoldTS, FadeTS;
  HeartbeatLEDToggle(millis());
  if (IsSwitchNewlyPressed(switchPin))
  {
    // Signal thread cycle color R-G-B
    nilSemSignal(&semRGB);
    if (PinWheel()) last_switch = false; // pretend switch isn't closed if interrupted. 
    HoldTS = millis();
  }
}

**Comment by dmemphis** [comment]
> /*
 * Example to demonstrate thread definition, semaphores, and thread sleep.
 */
#include <NilRTOS.h>

// The LED is attached to pin 13 on Arduino.
const uint8_t LED_PIN = 13;

// Declare a semaphore with an inital counter value of zero.
SEMAPHORE_DECL(sem, 0);
//------------------------------------------------------------------------------
/*
 * Thread 1, turn the LED off when signalled by thread 2.
 */
// Declare a stack with 128 bytes beyond context switch and interrupt needs.
NIL_WORKING_AREA(waThread1, 128);

// Declare the thread function for thread 1.
NIL_THREAD(Thread1, arg) {
  pinMode(LED_PIN, OUTPUT);  
  digitalWrite(LED_PIN, LOW);
  while (TRUE) {
    // Wait for signal from thread 2.
    if (nilSemWaitTimeout(&sem,1000) == NIL_MSG_TMO) {
        digitalWrite(LED_PIN, !digitalRead(LED_PIN)); // Toggle
    } else { // Signaled!  Blink fast
      for (int i=0; i < 5; i++) {      
          digitalWrite(LED_PIN, HIGH); 
          nilThdSleepMilliseconds(20);
          digitalWrite(LED_PIN, LOW); 
          nilThdSleepMilliseconds(20);  
      }
    }  
  }
}  

//------------------------------------------------------------------------------
/*
 * Thread 2, turn the LED on and signal thread 1 to turn the LED off.
 */
// Declare a stack with 128 bytes beyond context switch and interrupt needs. 
NIL_WORKING_AREA(waThread2, 128);

// Declare the thread function for thread 2.
NIL_THREAD(Thread2, arg) {
  while (TRUE) {    
    // Sleep  random milliseconds.   
    nilThdSleepMilliseconds(random (5000, 8000));
    
    // Signal thread 1 to turn LED off.
    nilSemSignal(&sem);
  }
}
//------------------------------------------------------------------------------
/*
 * Threads static table, one entry per thread.  A thread's priority is
 * determined by its position in the table with highest priority first.
 * 
 * These threads start with a null argument.  A thread's name may also
 * be null to save RAM since the name is currently not used.
 */
NIL_THREADS_TABLE_BEGIN()
NIL_THREADS_TABLE_ENTRY("thread1", Thread1, NULL, waThread1, sizeof(waThread1))
NIL_THREADS_TABLE_ENTRY("thread2", Thread2, NULL, waThread2, sizeof(waThread2))
NIL_THREADS_TABLE_END()
//------------------------------------------------------------------------------
void setup() {
  // Start Nil RTOS.
  nilSysBegin();
}
//------------------------------------------------------------------------------
// Loop is the idle thread.  The idle thread must not invoke any 
// kernel primitive able to change its state to not runnable.
void loop() {
  // Not used.
}

**Comment by dmemphis** [comment]
This reword of the nilBlink sketch illustrates it.
The LED should timeout every second waiting for a signal- which only comes
at a 3 hz rate.  When it experiences a timeout its supposed to TOGGLE the LED.
Every 3 seconds, it should get the signal and flash the LEDs fast.
So the LED should be toggling at 1hz rate and every 3 seconds doing a fast flash.
Because the return from the nilSemWaitTimeout is always OK, the toggle is never seen-
only the fast flashes, whether it timed out or got signaled so we get the fast flash
happening at about 1hz rate instead.

/*
 * Example to demonstrate thread definition, semaphores, and thread sleep.
 */
#include <NilRTOS.h>

// The LED is attached to pin 13 on Arduino.
const uint8_t LED_PIN = 13;

// Declare a semaphore with an inital counter value of zero.
SEMAPHORE_DECL(sem, 0);
//------------------------------------------------------------------------------
/*
 * Thread 1, turn the LED off when signalled by thread 2.
 */
// Declare a stack with 128 bytes beyond context switch and interrupt needs.
NIL_WORKING_AREA(waThread1, 128);

// Declare the thread function for thread 1.
NIL_THREAD(Thread1, arg) {
  pinMode(LED_PIN, OUTPUT);  
  digitalWrite(LED_PIN, LOW);
  while (TRUE) {
    // Wait for signal from thread 2.
    msg_t res = nilSemWaitTimeout(&sem,1000);
    if (res == NIL_MSG_OK) { // signaled - flash fast!
      for (int i=0; i < 5; i++) {      
          digitalWrite(LED_PIN, HIGH); 
          nilThdSleepMilliseconds(20);
          digitalWrite(LED_PIN, LOW); 
          nilThdSleepMilliseconds(20);        
      }
    } else if (res == NIL_MSG_TMO) { // Timed out - just toggle @ 1hz
        digitalWrite(LED_PIN, !digitalRead(LED_PIN)); 
    }  
  }
}  

//------------------------------------------------------------------------------
/*
 * Thread 2, turn the LED on and signal thread 1 to turn the LED off.
 */
// Declare a stack with 128 bytes beyond context switch and interrupt needs. 
NIL_WORKING_AREA(waThread2, 128);

// Declare the thread function for thread 2.
NIL_THREAD(Thread2, arg) {
  while (TRUE) {    
    // Sleep  random milliseconds.   
    nilThdSleepMilliseconds(3000);
    
    // Signal thread 1 to turn LED off.
    nilSemSignal(&sem);
  }
}
//------------------------------------------------------------------------------
/*
 * Threads static table, one entry per thread.  A thread's priority is
 * determined by its position in the table with highest priority first.
 * 
 * These threads start with a null argument.  A thread's name may also
 * be null to save RAM since the name is currently not used.
 */
NIL_THREADS_TABLE_BEGIN()
NIL_THREADS_TABLE_ENTRY("thread1", Thread1, NULL, waThread1, sizeof(waThread1))
NIL_THREADS_TABLE_ENTRY("thread2", Thread2, NULL, waThread2, sizeof(waThread2))
NIL_THREADS_TABLE_END()
//------------------------------------------------------------------------------
void setup() {
  // Start Nil RTOS.
  nilSysBegin();
}
//------------------------------------------------------------------------------
// Loop is the idle thread.  The idle thread must not invoke any 
// kernel primitive able to change its state to not runnable.
void loop() {
  // Not used.
}

**Comment by dmemphis** [comment]
FYI-
I reworked my original sketch to use two thread and not use the loop().  So its more
like the examples.  No change to the "failure". 
I also made it compilable under nil or Chibi interchangeably.
Under Chibi, using the same semantics, it works "correctly" -the way I expected the NIL version to work.

**Comment by dmemphis** [comment]
I think I inadvertently close this issue.
Nil is not behaving the same as Chibi with ...SemWaitTimeout.

**Comment by greiman** [comment]
I can reproduce the bug.  The problem will be to fix it.  This version of nil is very old so I can't ask for help since it was a preview version. 

It is not practical to just port a newer version of nil to Arduino.  New versions of nil and RT are great but don't coexist well with the Arduino core.

I have switched to ChibiStudio for my projects.

I will continue to look for the bug.  I would have expected it to be easy to find since semaphore timeouts return NIL_MSG_OK and successful cases return  NIL_MSG_TMO.  I have spent some time with no success so I need to enable some debug aids.

**Comment by dmemphis** [comment]
Interesting, thanks for trying.  I looked at it to try to fix it too, expecting to be able to spot what lead to this behavior easily, but no, it read good to me too.  

If you don't mind me asking, what are the challenges cooexisting well with the Arduino core?
Do they make changes in new releases that mess the RTOS's up?

I am only experimenting at this point and can
live with either one, and can run with RT for now. 
In fact the overhead is about the same too.  Not to much reason to choose one over the
other.  Of course if I run into a bug with RT I'll be in the same boat. 

I can also switch to Atmel Studio and use something else, but I must admit
it is SO nice in the Arduino IDE to flip the board type and download to a variant no fuss
no muss.  I don't think it can be quite that easy in Studio.  I'll look at ChibiStudio.

**Comment by greiman** [comment]
I have made some progress on understanding the bug.  It is subtle, this print statement added at line 325 of nil.c causes the proper return status.  Adding a delay() here doesn't change the status.

```
      if (nil.current->u1.msg == NIL_MSG_TMO) {
        NilDebug(__LINE__);
      }
```

NilDebug is this C callable function.

```
extern "C" void NilDebug(int);
void NilDebug(int n) {
  Serial.println(n);
}
```

There may be missing lock or an interaction with the Arduino use of timer0.   It could just be a bug in the old version of nil.

**Comment by dmemphis** [comment]
Ouch. Some kind of race condition perhaps.  
I can see that it could be a big deal to track that down.
I think it was great that the initial port got done on nil and chibi, thank you, 
I can't see how much of anyone can keep up with the related moving targets in open source... in your case 
Arduino core and nil core.   
I'll continue on with the chibi lib and see how it goes. I may not use that much more functionality
than I already have.  
I've not done a lot of contributing to repositories like this and don't know if this should close or not,
ie: its not fixed, but probably won't be- close it or leave it open?  Feel free to close it if thats
the norm.  Thanks VERY much for all the response here.

**Comment by greiman** [comment]
After a bit  more thinking I realized what's happening.  Most likely the new version of avr-gcc doesn't understand what the context switch function, port_switch(), does to memory.

Here is a fix to try, go to line 325 of nil.c and add a line like this:

```
      port_switch(ntr, otr);
      asm volatile ("" : : : "memory");  // Tell the compiler global memory could be changed.
      return nil.current->u1.msg;
```
I contacted Giovanni Di Sirio, the author of ChibiOS/nil,  and he sees the problem.  I will see if he has a better fix.

**Comment by greiman** [comment]
Giovanni Di Sirio had a better idea to keep nil.c pure with no AVR code.

Edit nilcore.h and at line 288 change the macro to this:

```
#define port_switch(ntp, otp) {_port_switch(ntp, otp); \
                               asm volatile ("" : : : "memory");}
```

**Comment by dmemphis** [comment]
Excellent and how interesting. So it s a optimizer issue then?
Funny I was exposed the the "memory block" to force execution order for the first time yesterday.
http://blog.regehr.org/archives/28
That kept your fix out of the nil.c, but that assumes, doesn't it, that in general nil.c is not going to generally
be exposed to other compilers that might behave like gcc? 
Frankly I don't know how there isn't a lot more embedded code broken by this sort of thing.
It makes a source/assembler debugger still a vital tools you can see if important stuff got optimized away.
I think I'd prefer to turn of optimization on certain sets of modules that are intended to be 
compiled verbatim than to sprinkle these memory blocks around the code.
Thanks so much, I'll apply the fix and move on!

**Comment by greiman** [comment]
You could call it an optimization issue but no compiler can be expected to cope with switching to a new thread then picking up when context is switched back.  what appears as a return from port_switch() is not a return but a context switch by the scheduler.

You can't read OS kernel code easily.  port_switch() swaps thread stacks so the return  is to totally different code  than to just after the port_swap() call.

By the way I am looking at porting the latest version of nil to AVR Arduino.  My contact with Giovanni Di Sirio opened my eyes to how he has designed flexibility into the new version.

**Comment by vysocan** [comment]
Hello,
just closely watching the discussion. I'm using nil on my ongoing project, and want to thank you for your work. It is amazing what you can do with AVR and nil.
So thanks :)

**Comment by dmemphis** [comment]
The fix works for me.  nilSemWaitTimeout is issuing NIL_MSG_TMO as it should.
Thanks again!

**Comment by greiman** [comment]
You might want to look at a new port of ChibiOS/Nil here.

https://github.com/greiman/ChNil

I started a new repo since the API is very different, more compatible with ChibiOS/RT.

**Comment by dmemphis** [comment]
Certainly!  I will be happy to check it out.
        Thanks for the heads up.
        -DC
    
    
    On 1/16/2017 3:25 PM, Bill Greiman
      wrote:
    
    
      You might want to look at a new port of ChibiOS/Nil here.
      https://github.com/greiman/ChNil
      I started a new repo since the API is very different, more
        compatible with ChibiOS/RT.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/greiman/NilRTOS-Arduino","title":"greiman/NilRTOS-Arduino","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/greiman/NilRTOS-Arduino"}},"updates":{"snippets":[{"icon":"PERSON","message":"@greiman in #3: You might want to look at a new port of ChibiOS/Nil here.\r\n\r\nhttps://github.com/greiman/ChNil\r\n\r\nI started a new repo since the API is very different, more compatible with ChibiOS/RT. "}],"action":{"name":"View Issue","url":"https://github.com/greiman/NilRTOS-Arduino/issues/3#issuecomment-272954601"}}}

**Comment by dmemphis** [comment]
Hi!
        I just tried it and found a potential problem with the port.
        Posted an issue there.
        DC
    
    
    On 1/16/2017 3:25 PM, Bill Greiman
      wrote:
    
    
      You might want to look at a new port of ChibiOS/Nil here.
      https://github.com/greiman/ChNil
      I started a new repo since the API is very different, more
        compatible with ChibiOS/RT.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/greiman/NilRTOS-Arduino","title":"greiman/NilRTOS-Arduino","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/greiman/NilRTOS-Arduino"}},"updates":{"snippets":[{"icon":"PERSON","message":"@greiman in #3: You might want to look at a new port of ChibiOS/Nil here.\r\n\r\nhttps://github.com/greiman/ChNil\r\n\r\nI started a new repo since the API is very different, more compatible with ChibiOS/RT. "}],"action":{"name":"View Issue","url":"https://github.com/greiman/NilRTOS-Arduino/issues/3#issuecomment-272954601"}}}
